<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

namespace Common\Library\Tests\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protobuf.Addr</code>
 */
class Addr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float lon = 1;</code>
     */
    protected $lon = 0.0;
    /**
     * Generated from protobuf field <code>float lat = 2;</code>
     */
    protected $lat = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type float $lon
     * @type float $lat
     * }
     */
    public function __construct($data = NULL)
    {
        \Common\Library\Tests\Protobuf\Book::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float lon = 1;</code>
     * @return float
     */
    public function getLon()
    {
        return $this->lon;
    }

    /**
     * Generated from protobuf field <code>float lon = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLon($var)
    {
        GPBUtil::checkFloat($var);
        $this->lon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float lat = 2;</code>
     * @return float
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Generated from protobuf field <code>float lat = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->lat = $var;

        return $this;
    }

}

