<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

namespace Common\Library\Tests\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Person  生成php文件的类名
 *
 * Generated from protobuf message <code>Protobuf.GetBookListData</code>
 */
class GetBookListData extends \Google\Protobuf\Internal\Message
{
    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *年龄
     *
     * Generated from protobuf field <code>int32 age = 2;</code>
     */
    protected $age = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>bool sex = 3;</code>
     */
    protected $sex = false;
    /**
     *手机
     *
     * Generated from protobuf field <code>int32 phone = 4;</code>
     */
    protected $phone = 0;
    /**
     * Generated from protobuf field <code>repeated .Protobuf.Addr addr = 5;</code>
     */
    private $addr;
    /**
     * Generated from protobuf field <code>int32 user_id = 6;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>map<string, .Protobuf.Addr> map_addr = 7;</code>
     */
    private $map_addr;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $name
     *          姓名
     * @type int $age
     *          年龄
     * @type bool $sex
     *          性别
     * @type int $phone
     *          手机
     * @type \Common\Library\Tests\Protobuf\Addr[]|\Google\Protobuf\Internal\RepeatedField $addr
     * @type int $user_id
     * @type array|\Google\Protobuf\Internal\MapField $map_addr
     * }
     */
    public function __construct($data = NULL)
    {
        \Common\Library\Tests\Protobuf\Book::initOnce();
        parent::__construct($data);
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *年龄
     *
     * Generated from protobuf field <code>int32 age = 2;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     *年龄
     *
     * Generated from protobuf field <code>int32 age = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>bool sex = 3;</code>
     * @return bool
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>bool sex = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkBool($var);
        $this->sex = $var;

        return $this;
    }

    /**
     *手机
     *
     * Generated from protobuf field <code>int32 phone = 4;</code>
     * @return int
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *手机
     *
     * Generated from protobuf field <code>int32 phone = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkInt32($var);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuf.Addr addr = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuf.Addr addr = 5;</code>
     * @param \Common\Library\Tests\Protobuf\Addr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\Library\Tests\Protobuf\Addr::class);
        $this->addr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 6;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .Protobuf.Addr> map_addr = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMapAddr()
    {
        return $this->map_addr;
    }

    /**
     * Generated from protobuf field <code>map<string, .Protobuf.Addr> map_addr = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMapAddr($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\Library\Tests\Protobuf\Addr::class);
        $this->map_addr = $arr;

        return $this;
    }

}

