<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

namespace Common\Library\Tests\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protobuf.PkgGetBookListReq</code>
 */
class PkgGetBookListReq extends \Google\Protobuf\Internal\Message
{
    /**
     *响应
     *
     * Generated from protobuf field <code>int32 book_id = 1;</code>
     */
    protected $book_id = 0;
    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     */
    protected $user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int $book_id
     *          响应
     * @type int $user_id
     * }
     */
    public function __construct($data = NULL)
    {
        \Common\Library\Tests\Protobuf\Book::initOnce();
        parent::__construct($data);
    }

    /**
     *响应
     *
     * Generated from protobuf field <code>int32 book_id = 1;</code>
     * @return int
     */
    public function getBookId()
    {
        return $this->book_id;
    }

    /**
     *响应
     *
     * Generated from protobuf field <code>int32 book_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBookId($var)
    {
        GPBUtil::checkInt32($var);
        $this->book_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

}

